# NUMPY ASSIGNMENT

### Question 1 – Student Marks Array
The marks obtained by five students in a subject are given as [78, 65, 89, 56, 92]. Create a NumPy array and display the array along with its basic properties


In [4]:
import  numpy as np
arr=np.array([78,65,89,56,92])
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(arr.shape)

int64
1
5
(5,)


### Question 2 – Student Marks Access
The marks of five students are stored in a NumPy array as [72, 85, 64, 90, 76]. Write a program to access and display specific student marks using NumPy indexing and slicing


In [6]:
arr=np.array([78,65,89,56,92])
print(arr[3])
print(arr[1:4])

56
[65 89 56]


### Question 3 – Subject-wise Marks
The marks obtained by five students in three subjects are given below. Create a NumPy array to represent the data and reshape it into an appropriate matrix format.
[78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92]


In [9]:
arr=np.array([78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92])
print(arr.reshape(5,3))

[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


### Question 4 – Internal and External Marks
The internal and external examination marks of five students are stored in two NumPy arrays. Write a program to calculate the final marks of each student using NumPy array operations


In [11]:
arr1=np.array([40,50,38,44,25])
arr2=np.array([44,34,23,50,32])
print(arr1+arr2)

[84 84 61 94 57]


### Question 5 – Pass Percentage Analysis
The marks obtained by five students are [45, 78, 56, 32, 91]. Using NumPy Boolean masking, identify the students who have secured 50 marks or above.


In [15]:
arr=np.array([45, 78, 56, 32, 91])

print(arr[arr>=50])

[78 56 91]


 ### Question 6 – Average Marks
The marks of five students in three subjects are represented using a NumPy matrix. Write a program to calculate the average marks of each student


In [17]:
arr=np.array([[78,85,90],
 [65 ,72 ,80],
 [88 ,91 ,84],
 [56 ,62 ,70],
 [95 ,89 ,90]])
print(np.mean(arr,axis=1))


[84.33333333 72.33333333 87.66666667 62.66666667 91.33333333]


### Question 7 – Class Performance Statistics
The marks obtained by five students are [67, 82, 91, 74, 58]. Using NumPy statistical functions, determine the total, average, highest, lowest, and standard deviation of the marks.


In [18]:
arr=np.array([67, 82, 91, 74, 58])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

372
74.4
91
58
11.46472851837321


### Question 8 – Subject-wise Performance
The marks of five students in three subjects are stored in a NumPy matrix. Write a program to calculate the total marks obtained in each subject using an appropriate axis operation


In [21]:
arr=np.array([[78,85,90],
 [65 ,72 ,80],
 [88 ,91 ,84],
 [56 ,62 ,70],
 [95 ,89 ,90]])
print(np.sum(arr,axis=0))

[382 399 414]


### Question 9 – Student-wise Performance
The marks of five students in three subjects are stored in a NumPy matrix. Write a program to calculate the total marks obtained by each student using an appropriate axis operation


In [22]:
arr=np.array([[78,85,90],
 [65 ,72 ,80],
 [88 ,91 ,84],
 [56 ,62 ,70],
 [95 ,89 ,90]])
print(np.sum(arr,axis=1))

[253 217 263 188 274]


### Question 10 – Student Ranking
The total marks obtained by five students are [245, 278, 219, 290, 256]. Use NumPy sorting and indexing operations to arrange the marks in order and determine the ranking of the students


In [30]:
arr=np.array([245, 278, 219, 290, 256])
print(np.argsort(arr))

[2 0 4 1 3]


### Question 11 – Duplicate Marks Analysis
The marks obtained by five students are [85, 92, 85, 76, 92]. Use NumPy functions to identify the unique marks obtained by the students


In [31]:
arr=np.array([85, 92, 85, 76, 92])
print(np.unique(arr))

[76 85 92]


### Question 12 – Missing Marks
The marks of five students are represented as [78, 85, np.nan, 92, 67], where np.nan represents a missing mark. Write a NumPy program to calculate the average marks without considering the missing value



In [33]:
arr=np.array( [78, 85, np.nan, 92, 67])
print(np.nanmean(arr))

80.5


### Question 13 – Grade Classification
The marks obtained by five students are [95, 82, 74, 61, 45]. Using NumPy conditional operations, classify the students into appropriate grade categories based on their marks.


In [8]:
import numpy as np
marks = np.array([95, 82, 74, 61, 45])
conditions = [marks >= 90,marks >= 80,marks >= 70, marks >= 60, marks < 60]
grades = ["A", "B", "C", "D", "F"]
result = np.select(conditions, grades, default="")
print(result)

['A' 'B' 'C' 'D' 'F']


### Question 14 – Random Marks Generation
Generate marks for five students using NumPy's random number generation functionality. Perform basic statistical analysis on the generated marks


In [4]:
import numpy as np
print(np.random.randint(0,100,5))


[13 49 27 76 81]


### Question 15 – Student Performance Analysis
The marks of five students in three subjects are stored in a NumPy array. Develop a program to perform a complete student performance analysis by calculating the total marks, average marks, highest marks, lowest marks, and identifying students who perform above the class average


In [11]:
arr=np.array([[78,85,90],
 [65 ,72 ,80],
 [88 ,91 ,84],
 [56 ,62 ,70],
 [95 ,89 ,90]])
print(np.sum(arr,axis=1))
print(np.mean(arr,axis=1))
print(np.max(arr,axis=1))
print(np.min(arr,axis=1))
average=np.mean(arr,axis=1)
class_average=np.mean(average)
print(average[average>class_average])


[253 217 263 188 274]
[84.33333333 72.33333333 87.66666667 62.66666667 91.33333333]
[90 80 91 70 95]
[78 65 84 56 89]
[84.33333333 87.66666667 91.33333333]
